[book]
authors = ["Jason Morelli-Harlan"]
language = "en"
multilingual = false
src = "src"
title = "Fungal Dreams"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.wavedrom]
command = "mdbook-wavedrom"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js", "wavedrom.min.js", "wavedrome-default.js"]
